name: Desktop CI

on:
  push:
    paths:
      - 'app/desktop/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'

jobs:
  build-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      # Let the action read the exact pnpm version from your root package.json "packageManager"
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build (desktop only)
        run: |
          pnpm --dir app/desktop run build
          pnpm --dir app/desktop run postbuild

      - name: Upload desktop dist
        uses: actions/upload-artifact@v4
        with:
          name: desktop-dist
          path: app/desktop/dist/**
