name: Desktop build & release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  packages: write

env:
  ELECTRON_VERSION: 29.4.6
  PNPM_VERSION: 9

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: pnpm‑store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: electron cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/electron
          key: ${{ runner.os }}-electron-${{ env.ELECTRON_VERSION }}

      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfuse2 rpm

      - name: Install deps (desktop)
        run: pnpm --dir app/desktop install --frozen-lockfile

      - name: Compile TypeScript
        run: pnpm --dir app/desktop run build

      # GH_TOKEN lets electron‑builder publish straight to the tag
      - name: Build & publish installers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm --dir app/desktop run dist
